"""Add password column to user table

Revision ID: 31417ea42d0c
Revises: a3e9cb2d0884
Create Date: 2021-10-27 14:27:03.571149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31417ea42d0c'
down_revision = 'a3e9cb2d0884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
